version: '3'
services:
        liquibase_db:
                image: postgres:13
                ports:
                        - 6432:5432
                env_file:
                        - database.env
                #network_mode: "host" 
                volumes:
                        - ./db:/var/lib/postgresql/data/
